package com.ems.employee_management_system.mappers;

import com.ems.employee_management_system.dtos.LocationRequestDTO;
import com.ems.employee_management_system.dtos.LocationResponseDTO;
import com.ems.employee_management_system.models.Location;

public class LocationMapper {
    /**
     * Converts Location entity to LocationResponseDTO
     */
    public static LocationResponseDTO toResponseDTO(Location location) {
        if (location == null) {
            return null;
        }
        
        LocationResponseDTO dto = new LocationResponseDTO();
        dto.setId(location.getId());
        dto.setName(location.getName());
        dto.setAddress(location.getAddress());
        dto.setCity(location.getCity());
        dto.setState(location.getState());
        dto.setCountry(location.getCountry());
        dto.setPostalCode(location.getPostalCode());
        return dto;
    }

    /**
     * Converts LocationRequestDTO to Location entity
     * ID is not set (auto-generated by JPA)
     */
    public static Location toEntity(LocationRequestDTO dto) {
        if (dto == null) {
            return null;
        }
        
        Location location = new Location();
        location.setName(dto.getName());
        location.setAddress(dto.getAddress());
        location.setCity(dto.getCity());
        location.setState(dto.getState());
        location.setCountry(dto.getCountry());
        location.setPostalCode(dto.getPostalCode());
        return location;
    }
} 