package com.ems.employee_management_system.config;

import com.ems.employee_management_system.models.User;
import com.ems.employee_management_system.repositories.UserRepository;
import com.ems.employee_management_system.utils.HashUtil;
import com.ems.employee_management_system.enums.UserRole;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;

@Configuration
public class DataInitializer {

    private static final Logger logger = LoggerFactory.getLogger(DataInitializer.class);

    @Bean
    CommandLineRunner initDatabase(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        return args -> {
            // Hash only admin password (matching frontend hashing)
            // Username stays plain for user-friendliness
            String hashedAdminPassword = HashUtil.hashPassword("admin123");
            String doubleHashedPassword = passwordEncoder.encode(hashedAdminPassword); // Double hash: frontend hash + BCrypt
            
            // Check if admin user already exists (by plain username)
            userRepository.findByUsername("admin").ifPresentOrElse(
                existingAdmin -> {
                    // Admin exists - update password to use new double-hashing method
                    logger.info("Admin user exists. Updating password to use new double-hashing method...");
                    existingAdmin.setPassword(doubleHashedPassword);
                    userRepository.save(existingAdmin);
                    logger.info("✅ Admin user password updated successfully!");
                    logger.info("   Username: admin");
                    logger.info("   Password: admin123 (now stored as double hash)");
                    logger.info("   Role: SYSTEM_ADMIN");
                },
                () -> {
                    // Admin doesn't exist - create new one
                    logger.info("Creating initial admin user...");
                    
                    User admin = new User();
                    // ID will be auto-generated by JPA (@GeneratedValue)
                    admin.setUsername("admin"); // Store plain username
                    admin.setPassword(doubleHashedPassword); // Double hash: frontend hash + BCrypt
                    admin.setEmail("admin@ems.com");
                    admin.setRole(UserRole.SYSTEM_ADMIN.getValue());
                    admin.setCreatedAt(LocalDateTime.now());
                    
                    userRepository.save(admin);
                    logger.info("✅ Initial admin user created successfully!");
                    logger.info("   Username: admin");
                    logger.info("   Password: admin123 (stored as double hash)");
                    logger.info("   Role: SYSTEM_ADMIN");
                    logger.info("   Note: Frontend will hash password before sending, username stays plain");
                }
            );
        };
    }
}

