package com.ems.employee_management_system.config;

import com.ems.employee_management_system.models.User;
import com.ems.employee_management_system.repositories.UserRepository;
import com.ems.employee_management_system.utils.HashUtil;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.time.LocalDateTime;

@Configuration
public class DataInitializer {

    private static final Logger logger = LoggerFactory.getLogger(DataInitializer.class);

    @Bean
    CommandLineRunner initDatabase(UserRepository userRepository, PasswordEncoder passwordEncoder) {
        return args -> {
            // Hash only admin password (matching frontend hashing)
            // Username stays plain for user-friendliness
            String hashedAdminPassword = HashUtil.hashPassword("admin123");
            
            // Check if admin user already exists (by plain username)
            if (userRepository.findByUsername("admin").isEmpty()) {
                logger.info("Creating initial admin user...");
                
                User admin = new User();
                // ID will be auto-generated by JPA (@GeneratedValue)
                admin.setUsername("admin"); // Store plain username
                admin.setPassword(passwordEncoder.encode(hashedAdminPassword)); // Double hash: frontend hash + BCrypt
                admin.setEmail("admin@ems.com");
                admin.setRole("SYSTEM_ADMIN");
                admin.setCreatedAt(LocalDateTime.now());
                
                userRepository.save(admin);
                logger.info("✅ Initial admin user created successfully!");
                logger.info("   Username: admin");
                logger.info("   Password: admin123 (stored as double hash)");
                logger.info("   Role: SYSTEM_ADMIN");
                logger.info("   Note: Frontend will hash password before sending, username stays plain");
            } else {
                logger.debug("Admin user already exists, skipping initialization.");
            }
        };
    }
}

